services:
  base:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: vrx-base

  builder:
    build:
      context: ../
      dockerfile: docker/Dockerfile.builder
    depends_on:
      - base
    image: vrx-builder:latest
 
  devel:
    build:
      context: .
      dockerfile: Dockerfile.devel
    depends_on:
      - base
    image: vrx-devel:latest
    network_mode: host
    stdin_open: true 
    tty: true
    user: ubuntu
    group_add:
      - video
      - sudo
    # TODO: support for intel by enabling /dev/dri
    # devices:  # for intel dri
    #  - /dev/dri
    environment:
      - DISPLAY=unix${DISPLAY}
      - TERM=xterm-256color
    volumes:
      - ..:/ws/src
      - /sys:/sys:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev/log:/dev/log:ro
      - /run/log:/run/log:ro
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: bash
