# Ubuntu 24.04 
FROM osrf/ros:jazzy-desktop AS vrx-base

# Workaround from https://discourse.ros.org/t/ros-signing-key-migration-guide/43937
RUN rm -f /etc/apt/sources.list.d/ros2-latest.list \
  && rm -f /usr/share/keyrings/ros2-latest-archive-keyring.gpg

# Only install ros2-apt-source if it's not already installed
RUN if ! dpkg -l | grep -q ros2-apt-source; then \
    apt-get update && \
    apt-get install -y ca-certificates curl && \
    export ROS_APT_SOURCE_VERSION=$(curl -s https://api.github.com/repos/ros-infrastructure/ros-apt-source/releases/latest | grep -F "tag_name" | awk -F\" '{print $4}') && \
    curl -L -s -o /tmp/ros2-apt-source.deb "https://github.com/ros-infrastructure/ros-apt-source/releases/download/${ROS_APT_SOURCE_VERSION}/ros2-apt-source_${ROS_APT_SOURCE_VERSION}.$(. /etc/os-release && echo $VERSION_CODENAME)_all.deb" && \
    apt-get update && \
    apt-get install /tmp/ros2-apt-source.deb && \
    rm -f /tmp/ros2-apt-source.deb; \
  fi

ENV DEBIAN_FRONTEND=noninteractive

# Setup timezone
ENV TZ=Etc/UTC
RUN echo $TZ > /etc/timezone && \
    ln -fs /usr/share/zoneinfo/$TZ /etc/localtime && \
    apt update && \
    apt install -y locales && \
    locale-gen en_US en_US.UTF-8 && \
    update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8

# Set up repo to install Gazebo
RUN curl -s https://packages.osrfoundation.org/gazebo.gpg -o /usr/share/keyrings/pkgs-osrf-archive-keyring.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/pkgs-osrf-archive-keyring.gpg] http://packages.osrfoundation.org/gazebo/ubuntu-stable $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/gazebo-stable.list > /dev/null

# Install some 'standard' ROS packages and utilities.
RUN apt update \
    && apt install -y --no-install-recommends \
       gz-harmonic \
    && rm -rf /var/lib/apt/lists/* \
    && apt clean -qq

# copy the gz.repos file to the container
ADD gz.repos /tmp/gz.repos

# Need to compile ros_gz and gz_ros2_control from source for Gazebo Harmonic
#
RUN mkdir -p ~/ros_gz_ws/src \
    && cd ~/ros_gz_ws/src \
    && vcs import . < /tmp/gz.repos \
    && git clone https://github.com/gazebosim/ros_gz.git -b jazzy \
    && rm -r ros_gz/ros_gz_sim_demos \
    && apt update \
    && apt-mark hold ros-jazzy-gz-sim-vendor ros-jazzy-gz-physics-vendor ros-jazzy-gz-launch-vendor ros-jazzy-gz-sensors-vendor ros-jazzy-sdformat-vendor \
    && rosdep install -r --from-paths . --ignore-src --rosdistro jazzy -y --skip-keys="gz_sim_vendor gz_physics_vendor gz_launch_vendor gz_sensors_vendor sdformat_vendor ros_gz_sim_demos" \
    && rm -rf /var/lib/apt/lists/* \
    && apt clean -qq
RUN cd ~/ros_gz_ws \
    && . /opt/ros/jazzy/setup.sh \
    && colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release
