/*
 * Copyright (C) 2026 Open Source Robotics Foundation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 */

#ifndef GZ_SIM_WAVES_FFTWAVESIMULATION_HH_
#define GZ_SIM_WAVES_FFTWAVESIMULATION_HH_

#include <cstddef>
#include <cstdint>
#include <memory>

#include <Eigen/Dense>

#include "gz/sim/waves/WaveSimulation.hh"

namespace gz::sim::waves
{

struct WaveParameters;

/// \brief Stochastic FFT-based wave model backed by the Apache-2.0 EncinoWaves
/// spectral library (Horvath 2015): the inverse 2D FFT of an empirically
/// modelled directional spectrum (TMA/JONSWAP/PM + directional spreading +
/// dispersion), selected via the <spectrum>/<spreading>/<dispersion> params.
///
/// The output is a periodic tile of size `tileSize × tileSize` metres.
/// Queries outside the tile are wrapped via `fmod`. Each call to `Update`
/// regenerates the grid for that time; per-point queries (`Elevation`,
/// `ParticleVelocity`, ...) bilinear-sample the stored grid.
class FFTWaveSimulation final : public IWaveField
{
public:
  /// \brief Default-construct an unconfigured field. Call `SetParameters`
  /// before `Update`/sampling. Used by the engine factory (`MakeFFTWaveField`).
  FFTWaveSimulation();

  /// \brief Construct from spectrum / wind parameters.
  /// \param[in] _params Wave parameters; uses `direction` as the wind heading
  ///   and derives wind speed from `period` (deep-water PMS relation:
  ///   V19 ≈ 0.879·g/omegaP). `gain` scales spectrum amplitudes uniformly.
  /// \param[in] _tileSize Physical tile extent in metres; the wave field is
  ///   periodic with this period along both x and y.
  /// \param[in] _gridSize Resolution per axis (must be a power of two for
  ///   the FFT path; 64, 128, 256 typical).
  /// \param[in] _seed RNG seed for the Gaussian-distributed amplitudes; same
  ///   seed → same wave field bit-for-bit across runs.
  FFTWaveSimulation(const WaveParameters &_params,
                    double _tileSize,
                    std::size_t _gridSize,
                    std::uint32_t _seed);

  /// \brief Destructor (out-of-line so the EncinoState pimpl stays in the .cc).
  ~FFTWaveSimulation() override;

  // IWaveField
  void SetParameters(const WaveParameters &_params) override;
  double Elevation(double x, double y, double t) const override;
  gz::math::Vector3d ParticleVelocity(
    double x, double y, double t) const override;
  gz::math::Vector3d Normal(double x, double y, double t) const override;
  double Jacobian(double x, double y, double t) const override;
  void Update(double simTime) override;
  std::string_view Kind() const override { return "fft"; }
  std::optional<TileSize> Bounds() const override
  {
    return TileSize{this->tileSize_, this->tileSize_};
  }
  const WaveField2D *Field() const override;

  // ---- Accessors for unit tests + visual heightmap upload ----------------

  /// \brief Grid resolution per axis (power of two).
  std::size_t GridSize() const { return this->gridSize_; }
  /// \brief Physical tile extent per axis [m]; the field is periodic with it.
  double TileSizeMeters() const { return this->tileSize_; }

  /// \brief Surface elevation field η(x, y, t), refreshed by Update().
  const Eigen::MatrixXd &HeightGrid() const { return this->heightGrid_; }
  /// \brief Horizontal x-displacement field Dx(x, y, t), refreshed by Update().
  /// Multiplied by a "choppiness" factor in the visual shader to sharpen
  /// crests (Tessendorf 2001, eq. 29). Same grid layout as `HeightGrid()`.
  const Eigen::MatrixXd &DispXGrid() const { return this->dispXGrid_; }
  /// \brief Horizontal y-displacement field Dy(x, y, t).
  const Eigen::MatrixXd &DispYGrid() const { return this->dispYGrid_; }

private:
  /// \brief Bilinear sample of `grid` at the given world (x, y), wrapping
  /// queries outside the tile to its periodic image.
  double BilinearSample(const Eigen::MatrixXd &grid,
                        double x, double y) const;

  // Configuration. Default member-inits keep a default-constructed instance
  // benign until SetParameters() runs (the factory path).
  double        tileSize_{200.0};
  std::size_t   gridSize_{128};
  double        windSpeed_{0.0};
  double        gain_{1.0};
  double        tau_{2.0};

  // Per-update height grid (real domain), regenerated by Update(t)
  Eigen::MatrixXd heightGrid_;
  // Per-update horizontal displacement grids (Tessendorf eq. 29). Used by
  // the visual shader to produce choppy, asymmetric wave crests.
  Eigen::MatrixXd dispXGrid_;
  Eigen::MatrixXd dispYGrid_;
  // Folding / whitecap metric (Encino path): per-cell minimum eigenvalue of
  // the displacement Jacobian, 1 = flat. Sampled by Jacobian() → FoamMask().
  Eigen::MatrixXd minEGrid_;

  // Column-major view into the grids above, returned by Field() as the
  // backend-agnostic rendering contract. Repopulated on each call from the
  // current grid data() — Update reassigns the grids, so a cached pointer
  // would dangle. Mutable because Field() is const.
  mutable WaveField2D field_;

  // EncinoWaves-backed Update state. The EncinoState type is defined entirely
  // in FFTWaveSimulation.cc so the vendored EncinoWaves headers don't leak
  // into the public include surface here.
  struct EncinoState;
  std::unique_ptr<EncinoState> encino_;

  // Physics-based amplitude calibration for the Encino path. EncinoWaves'
  // `amplitudeGain` does not scale its height/displacement output, and its
  // intrinsic field variance is far larger than a physical sea state at our
  // wind speeds. We measure Encino's intrinsic RMS once at construction and
  // store the factor that rescales the significant wave height to the
  // standard fully-developed Pierson-Moskowitz wind-sea relation
  // (Hs = 0.21 * V19.5^2 / g). Applied to η/Dx/Dy every Update.
  double encinoScale_{1.0};

  // Time of the last Update(). The field at a given time is deterministic, so
  // Update() short-circuits on a repeat call for the same time. This lets
  // several consumers (the Waves system plus each WaveBuoyancy that advances
  // the field instance it holds — see the cross-process note in WaveBuoyancy)
  // converge on one FFT per tick instead of one per consumer. -1 = never
  // updated (sim time is always >= 0).
  double lastUpdateT_{-1.0};
};

/// \brief Factory: a default-constructed FFT wave-field engine (apply
/// `SetParameters` before use). Registered under the "fft" token so
/// `CreateWaveSimulation` can rebuild the engine from a serialized `Wavefield`
/// component on the GUI side.
std::shared_ptr<IWaveField> MakeFFTWaveField();

}  // namespace gz::sim::waves

#endif  // GZ_SIM_WAVES_FFTWAVESIMULATION_HH_
