<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:macro name="wamv_camera" params="name x:=0.5 y:=0 z:=1.5 R:=0 P:=0 Y:=0">
    <link name="${name}_link">
      <visual name="${name}_visual">
        <xacro:property name="visual_length" value="0.05" />
        <origin xyz="-${visual_length/2.0} 0 0" rpy="0 1.57 0" />
        <geometry>
          <cylinder radius="0.01" length="${visual_length}" />
        </geometry>
        <material name="${name}_visual_material">
          <color rgba="1.0 1.0 0.0 1.0" />
        </material>
      </visual>
    </link>
    <joint name="${name}_joint" type="fixed">
      <origin xyz="${x} ${y} ${z}" rpy="${R} ${P} ${Y}"/>
      <parent link="base_link"/>
      <child link="${name}_link"/>
    </joint>
    <link name="${name}_link_optical" />
    <joint name="${name}_optical_joint" type="fixed">
      <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}" />
      <parent link="${name}_link"/>
      <child link="${name}_link_optical"/>
    </joint>
    <gazebo reference="${name}_link">
      <sensor type="camera" name="${name}_sensor">
        <update_rate>30.0</update_rate>
        <camera name="${name}_camera">
          <horizontal_fov>1.3962634</horizontal_fov>
          <image>
            <width>800</width>
            <height>800</height>
            <format>R8G8B8</format>
          </image>
          <clip>
            <near>0.02</near>
            <far>300</far>
          </clip>
          <noise>
            <type>gaussian</type>
            <!-- Noise is sampled independently per pixel on each frame.
                 That pixel's noise value is added to each of its color
                 channels, which at that point lie in the range [0,1]. -->
            <mean>0.0</mean>
            <stddev>0.007</stddev>
          </noise>
        </camera>
        <plugin name="camera_plugin_${name}" filename="libgazebo_ros_camera.so">
          <alwaysOn>true</alwaysOn>
          <updateRate>0.0</updateRate>
          <cameraName>${name}</cameraName>
          <imageTopicName>image_raw</imageTopicName>
          <cameraInfoTopicName>camera_info</cameraInfoTopicName>
          <frameName>${name}_link_optical</frameName>
          <hackBaseline>0.07</hackBaseline>
          <distortionK1>0.0</distortionK1>
          <distortionK2>0.0</distortionK2>
          <distortionK3>0.0</distortionK3>
          <distortionT1>0.0</distortionT1>
          <distortionT2>0.0</distortionT2>
        </plugin>
      </sensor>
    </gazebo>
  </xacro:macro>
</robot>
